version: '3.7'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=my_database
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    secrets:
      - db-password

  backend:
    build: ./backend
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db
    secrets:
      - db-password

  frontend:
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend

secrets:
  db-password:
    file: ./db/password.txt
