apiVersion: apps/v1

kind: Deployment

metadata:
  name: flaskapp-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      flask: app

  template:
    metadata:
      labels:
        flask: app

    spec:
      containers:
      - name: flaskapp-container
        image: arielforner/flaskapp-k8s-practice:v1

        ports:
        - containerPort: 5200
---
apiVersion: v1

kind: Service

metadata:
  name: external-node-port

spec:
  type: NodePort
  
  selector:
    flask: app

  ports:
  - port: 5200
    targetPort: 5200
    nodePort: 31311
