version: '3'
services:
  frontend:
    image: nginx
    ports:
      - 8888:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command: /bin/bash -c "envsubst '$$FLASK_SERVER_ADDR' < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    depends_on:
      - backend

  backend:
    build: ./flask
    environment:
      - FLASK_SERVER_PORT=9091
    ports:
      - 9091:9091
    depends_on:
      - database
    
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - flask-app-vol:/data/db

volumes:
  flask-app-vol:
