pipeline {
    agent {
        docker {
            image 'python'
            args '-p 5000:5000 -u root'
            }
        parameters{
            string(name: 'NAME', defaultValue: '', description: '')
        }
        }
    stages {
        stage('checkout'){
            steps{
                checkout([$class: 'GitSCM',
                        branches: [[name: 'master']],
                        userRemoteConfigs: [[url: 'https://github.com/example/repo.git']]])
            }
        }
        // stage('cd: change directory') {
        //     steps {
        //             sh 'echo cd ${WORKSPACE}/DevSecOpsBIU12/DevOpsTechnologies/Jenkins/flask_app"'
        //             dir("${WORKSPACE}/DevSecOpsBIU12/DevOpsTechnologies/Jenkins/flask_app") {
        //         }
        //     }
        // }
        stage('build'){
            steps{
                sh 'echo Running "pip install -r requirements.txt"'
                sh 'sudo pip install -r requirements.txt'
                sh 'echo Running "main.py"'
                sh 'python3 main.py'
            }
        }
        stage('test'){
            steps{
                sh 'echo testing...'
                sh 'pytest test.py'
            }
        }
        stage('build an image'){
            when{
                branch 'dev'
            }
            agent{
                dockerfile true
            }
            steps{
                sh 'echo building image'
            }
        }
        stage('post'){
            when{
                params.NAME == 'ariel'
            }
            steps{
                echo "post $params.NAME"
            }
        }
    }
}