apiVersion: v1

kind: Pod

metadata:
  name: client-pod
  labels:
    client: web

spec:
  containers:
    - name: client
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
