Pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                sh 'pip install requests'
                sh 'python3 requests/http_e.py'
            }
        }
        stage('test') {
            steps {
                sh 'pip install pytest'
                sh 'pytest requests/TestRest'
            }
        }
        stage('deploy') {
            steps {
                sh 'docker build -t first_jenkins_project request/.'
            }
        }
    }
}
