apiVersion: v1
kind: Service

metadata:
  name: big-service

spec:
  type: NodePort
  selector:
    name: big
  ports:
  # internal port
  - port: 4000
    # container port
    targetPort: 3000
    # exposed (external) port
    nodePort: 31234
