apiVersion: v1
kind: Pod

metadata:
  name: big-pod
  labels:
    name: big

spec:
  containers:
  - name: big-container
    image: big:v1
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3000
